DROP TABLE PILL_SCHEDULE;
DROP TABLE PILL_OCCURANCE;

CREATE TABLE PILL_SCHEDULE(
	NAME INT NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL
);

CREATE TABLE PILL_OCCURANCE(
	SCHEDULE_ID INT NOT NULL,
	OCCURANCE_TIME TIME NOT NULL
);