CREATE TABLE PILL_SCHEDULE(
	SCHEDULE_ID INT NOT NULL UNIQUE,
	NAME INT NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL
);

CREATE TABLE PILL_OCCURANCE(
	OCCURANCE_ID INT NOT NULL UNIQUE,
	SCHEDULE_ID INT NOT NULL,
	OCCURANCE_TIME DATE NOT NULL,
)